import {FormEvent,useEffect,useState} from "react";
import type {IpdAdmission} from "../../api/ipd.api";
import type {DoctorSummary} from "../../types/reception-opd";
import * as api from "../../api/ipd-integrations.api";
type M="lab"|"radiology"|"ot"|"pharmacy"|"billing";
const money=(v:any)=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const dn=(d:any)=>[d?.title,d?.employee?.firstName??d?.firstName,d?.employee?.lastName??d?.lastName].filter(Boolean).join(" ")||d?.doctorCode||"Doctor";
export default function IpdIntegrationsPanel({admission,doctors,onDone}:{admission:IpdAdmission;doctors:DoctorSummary[];onDone:()=>Promise<void>}){
 const [m,setM]=useState<M>("lab"),[masters,setMasters]=useState<any[]>([]),[aux,setAux]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 async function load(){
  try{setErr("");let a:any[]=[],b:any[]=[],h:any={items:[]};
   if(m==="lab"){a=await api.listLabTests();h=await api.listLabOrders(admission.patientId)}
   if(m==="radiology"){a=await api.listRadiologyProcedures();h=await api.listRadiologyOrders(admission.patientId)}
   if(m==="ot"){a=await api.listOtRooms();b=await api.listOtProcedures();h=await api.listOtBookings(admission.patientId)}
   if(m==="pharmacy")a=await api.listPharmacyInventory(admission.branchId);
   if(m==="billing"){a=await api.listBillingServices();h=await api.listPatientInvoices(admission.patientId)}
   setMasters(a);setAux(b);setHistory(Array.isArray(h)?h:(h?.items||[]));
  }catch(e){setErr(e instanceof Error?e.message:"Unable to load module")}
 }
 useEffect(()=>{setSelected([]);void load()},[m,admission.id]);
 async function run(fn:()=>Promise<any>,ok:string){try{setBusy(true);setErr("");await fn();setMsg(ok);await load();await onDone()}catch(e){setErr(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 return <div className="ipd-integration"><nav className="ipd-integration-tabs">{([["lab","Laboratory"],["radiology","Radiology"],["ot","Operation Theatre"],["pharmacy","Pharmacy"],["billing","Billing"]] as [M,string][]).map(([k,l])=><button className={m===k?"active":""} onClick={()=>setM(k)} key={k}>{l}</button>)}</nav>
 {err&&<div className="ipd-alert error">{err}</div>}{msg&&<div className="ipd-alert success">{msg}</div>}
 {m==="lab"&&<OrderChoices title="Order Laboratory Tests" items={masters} selected={selected} toggle={toggle} label={x=>x.testName} meta={x=>`${x.sampleType} · ${money(x.price)}`} busy={busy} action={()=>run(()=>api.createLabOrder({branchId:admission.branchId,departmentId:admission.departmentId,doctorId:admission.doctorId,patientId:admission.patientId,ipdAdmissionId:admission.id,priority:"ROUTINE",testIds:selected}),"Lab order sent from IPD")} history={history}/>}
 {m==="radiology"&&<OrderChoices title="Order Radiology" items={masters} selected={selected} toggle={toggle} label={x=>x.procedureName} meta={x=>`${x.modality} · ${money(x.price)}`} busy={busy} action={()=>run(()=>api.createRadiologyOrder({branchId:admission.branchId,departmentId:admission.departmentId,doctorId:admission.doctorId,patientId:admission.patientId,ipdAdmissionId:admission.id,priority:"ROUTINE",provisionalDiagnosis:admission.provisionalDiagnosis||null,requestedProcedureIds:selected}),"Radiology order sent from IPD")} history={history}/>}
 {m==="ot"&&<Ot admission={admission} doctors={doctors} rooms={masters} procedures={aux} busy={busy} run={run} history={history}/>}
 {m==="pharmacy"&&<Pharmacy admission={admission} inventory={masters} busy={busy} run={run}/>}
 {m==="billing"&&<Billing admission={admission} services={masters} busy={busy} run={run} history={history}/>}
 </div>
}
function OrderChoices({title,items,selected,toggle,label,meta,busy,action,history}:{title:string;items:any[];selected:string[];toggle:(x:string)=>void;label:(x:any)=>string;meta:(x:any)=>string;busy:boolean;action:()=>void;history:any[]}){return <div className="ipd-work-grid"><section className="ipd-panel"><Head title={title}/><div className="ipd-choice-grid">{items.map(x=><button type="button" className={selected.includes(x.id)?"selected":""} onClick={()=>toggle(x.id)} key={x.id}><span>{selected.includes(x.id)?"✓":"+"}</span><div><strong>{label(x)}</strong><small>{meta(x)}</small></div></button>)}</div><div className="ipd-form-actions"><button disabled={busy||!selected.length} onClick={action}>Send Order</button></div></section><Hist rows={history}/></div>}
function Ot({admission,doctors,rooms,procedures,busy,run,history}:any){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>api.createOtBooking({branchId:admission.branchId,patientId:admission.patientId,ipdAdmissionId:admission.id,otRoomId:f.get("room"),procedureId:f.get("procedure"),priority:f.get("priority"),scheduledStart:f.get("start"),scheduledEnd:f.get("end"),primarySurgeonId:f.get("surgeon"),anaesthetistId:f.get("anaesthetist")||null,preOperativeDiagnosis:admission.provisionalDiagnosis||null}),"OT booking created from IPD")};return <div className="ipd-work-grid"><form className="ipd-panel" onSubmit={submit}><Head title="Schedule Operation Theatre"/><div className="ipd-form-grid"><Sel name="room" label="OT Room" a={rooms} t={(x:any)=>x.roomName}/><Sel name="procedure" label="Procedure" a={procedures} t={(x:any)=>`${x.procedureName} · ${money(x.baseCharge)}`}/><Sel name="surgeon" label="Primary Surgeon" a={doctors} t={dn}/><Sel name="anaesthetist" label="Anaesthetist" a={doctors} t={dn} optional/><label className="ipd-field"><span>Priority</span><select name="priority"><option>ELECTIVE</option><option>URGENT</option><option>EMERGENCY</option></select></label><Fld name="start" label="Start" type="datetime-local"/><Fld name="end" label="End" type="datetime-local"/></div><div className="ipd-form-actions"><button disabled={busy}>Create OT Booking</button></div></form><Hist rows={history}/></div>}
function Pharmacy({admission,inventory,busy,run}:any){const [mid,setMid]=useState(""),[bid,setBid]=useState("");const med=inventory.find((x:any)=>x.id===mid);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),batch=med?.batches.find((x:any)=>x.id===bid);if(!batch)return;run(()=>api.dispenseIpdMedicines({branchId:admission.branchId,patientId:admission.patientId,ipdAdmissionId:admission.id,items:[{medicineId:mid,batchId:bid,prescribedQuantity:Number(f.get("qty")),dispensedQuantity:Number(f.get("qty")),unitPrice:Number(batch.sellingPrice),instructions:f.get("instructions")||null}]}),"Medicine dispensed; pharmacy stock deducted")};return <form className="ipd-panel" onSubmit={submit}><Head title="Dispense from Pharmacy Stock"/><div className="ipd-form-grid"><label className="ipd-field"><span>Medicine</span><select required value={mid} onChange={e=>{setMid(e.target.value);setBid("")}}><option value="">Select</option>{inventory.map((x:any)=><option value={x.id} key={x.id}>{x.brandName} {x.strength||""}</option>)}</select></label><label className="ipd-field"><span>Batch</span><select required value={bid} onChange={e=>setBid(e.target.value)}><option value="">Select</option>{med?.batches?.filter((x:any)=>Number(x.availableQuantity)>0).map((x:any)=><option value={x.id} key={x.id}>{x.batchNumber} · Stock {x.availableQuantity} · {money(x.sellingPrice)}</option>)}</select></label><Fld name="qty" label="Quantity" type="number"/><Fld name="instructions" label="Instructions"/></div><div className="ipd-form-actions"><button disabled={busy||!bid}>Dispense & Deduct Stock</button></div></form>}
function Billing({admission,services,busy,run,history}:any){const bed=admission.bedAllocations.find((x:any)=>x.status==="ACTIVE")?.bed||admission.bedAllocations.at(-1)?.bed;const days=Math.max(1,Math.ceil(((admission.dischargedAt?new Date(admission.dischargedAt).getTime():Date.now())-new Date(admission.admissionDate).getTime())/86400000)),rate=Number(bed?.dailyCharge??bed?.room?.dailyCharge??0);const [sid,setSid]=useState("");const svc=services.find((x:any)=>x.id===sid);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const items:any[]=[];if(rate)items.push({sourceModule:"IPD",sourceEntityId:admission.id,description:`IPD Bed Charges - ${bed?.bedName||""}`,quantity:days,unitPrice:rate});if(svc)items.push({serviceId:svc.id,sourceModule:"IPD",sourceEntityId:admission.id,description:svc.serviceName,quantity:1,unitPrice:Number(svc.basePrice),taxPercent:svc.gstPercent==null?null:Number(svc.gstPercent)});run(()=>api.createIpdInvoice({branchId:admission.branchId,patientId:admission.patientId,ipdAdmissionId:admission.id,discountAmount:0,roundOffAmount:0,notes:`IPD ${admission.admissionNumber}`,items}),"IPD invoice generated in Billing")};return <div className="ipd-work-grid"><form className="ipd-panel" onSubmit={submit}><Head title="Generate IPD Billing Invoice"/><div className="ipd-bill-preview"><div><span>Stay</span><strong>{days} day(s)</strong></div><div><span>Bed Rate</span><strong>{money(rate)}/day</strong></div><div><span>Bed Charges</span><strong>{money(days*rate)}</strong></div></div><label className="ipd-field"><span>Additional Billing Service</span><select value={sid} onChange={e=>setSid(e.target.value)}><option value="">None</option>{services.map((x:any)=><option value={x.id} key={x.id}>{x.serviceName} · {money(x.basePrice)}</option>)}</select></label><div className="ipd-form-actions"><button disabled={busy||(!rate&&!svc)}>Generate Invoice</button></div></form><Hist rows={history}/></div>}
function Head({title}:{title:string}){return <div className="ipd-panel-head"><div><span>CONNECTED MODULE</span><h3>{title}</h3></div></div>}
function Hist({rows}:{rows:any[]}){return <section className="ipd-panel"><Head title="Connected Patient History"/><div className="ipd-record-list">{rows.map(x=><article key={x.id}><header><strong>{x.orderNumber||x.bookingNumber||x.invoiceNumber||x.id}</strong><span>{x.status}</span></header><p>{x.priority||x.notes||"Connected record"}</p></article>)}{!rows.length&&<div className="ipd-empty">No connected records yet.</div>}</div></section>}
function Sel({name,label,a,t,optional=false}:any){return <label className="ipd-field"><span>{label}</span><select name={name} required={!optional}><option value="">{optional?"None":"Select"}</option>{a.map((x:any)=><option value={x.id} key={x.id}>{t(x)}</option>)}</select></label>}
function Fld({name,label,type}:any){return <label className="ipd-field"><span>{label}</span><input name={name} type={type} required={type==="datetime-local"||type==="number"}/></label>}
