import {FormEvent,useEffect,useMemo,useState} from "react";
import {createBillingService,getBillingInvoice,listBillingInvoices,listBillingServices,recordBillingPayment,type BillingInvoice,type BillingService} from "../api/billing.api";
import "../styles/billing.css";
const pn=(p:any)=>[p?.firstName,p?.middleName,p?.lastName].filter(Boolean).join(" ")||"Patient";const money=(v:any)=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
export default function BillingPage(){const [tab,setTab]=useState<"invoices"|"services">("invoices"),[invoices,setInvoices]=useState<BillingInvoice[]>([]),[services,setServices]=useState<BillingService[]>([]),[selected,setSelected]=useState<BillingInvoice|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const [i,s]=await Promise.all([listBillingInvoices(),listBillingServices()]);setInvoices(i.items);setServices(s)}catch(e){setError(e instanceof Error?e.message:"Unable to load billing")}}useEffect(()=>{void load()},[]);
 async function open(id:string){setSelected(await getBillingInvoice(id))}async function run(fn:()=>Promise<any>,ok:string){try{setBusy(true);setError("");await fn();setMessage(ok);await load();if(selected)setSelected(await getBillingInvoice(selected.id))}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
 const k=useMemo(()=>({total:invoices.length,billed:invoices.reduce((a,x)=>a+Number(x.totalAmount),0),paid:invoices.reduce((a,x)=>a+Number(x.paidAmount),0),due:invoices.reduce((a,x)=>a+Number(x.balanceAmount),0),open:invoices.filter(x=>!["PAID","CANCELLED","REFUNDED"].includes(x.status)).length}),[invoices]);
 return <div className="hms-module-page"><header className="hms-module-hero"><div><span>REVENUE CYCLE</span><h1>Billing & Payments</h1><p>Patient invoices, IPD/OPD charges, payments, service catalogue and outstanding balances.</p></div><button onClick={()=>setTab("services")}>Service Catalogue</button></header>{error&&<div className="hms-alert error">{error}</div>}{message&&<div className="hms-alert success">{message}</div>}<section className="hms-kpis"><K l="Invoices" v={k.total}/><K l="Gross billed" v={money(k.billed)}/><K l="Collected" v={money(k.paid)}/><K l="Outstanding" v={money(k.due)}/><K l="Open bills" v={k.open}/></section><nav className="hms-tabs"><button className={tab==="invoices"?"active":""} onClick={()=>setTab("invoices")}>Invoices & Collections</button><button className={tab==="services"?"active":""} onClick={()=>setTab("services")}>Service Catalogue</button></nav>
 {tab==="invoices"?<section className="hms-card"><div className="hms-card-head"><div><span>COLLECTION QUEUE</span><h2>Patient Invoices</h2></div></div><div className="hms-table-wrap"><table className="hms-table"><thead><tr><th>Invoice</th><th>Patient</th><th>Source</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th/></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><strong>{i.invoiceNumber}</strong><small>{new Date(i.invoiceDate).toLocaleDateString("en-IN")}</small></td><td><strong>{pn(i.patient)}</strong><small>{i.patient.uhid||""}</small></td><td>{i.ipdAdmissionId?<span className="hms-pill warn">IPD</span>:<span className="hms-pill">OPD / Other</span>}</td><td>{money(i.totalAmount)}</td><td>{money(i.paidAmount)}</td><td><strong>{money(i.balanceAmount)}</strong></td><td><span className={`hms-pill ${i.status==="PAID"?"good":""}`}>{i.status.replaceAll("_"," ")}</span></td><td><button className="hms-action" onClick={()=>void open(i.id)}>Open</button></td></tr>)}</tbody></table></div></section>:<ServiceMaster services={services} busy={busy} run={run}/>}
 {selected&&<InvoiceModal invoice={selected} busy={busy} close={()=>setSelected(null)} run={run}/>}</div>}
function K({l,v}:any){return <article className="hms-kpi"><span>{l}</span><strong>{v}</strong></article>}
function ServiceMaster({services,busy,run}:any){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createBillingService({serviceCode:f.get("code"),serviceName:f.get("name"),moduleCode:f.get("module"),description:f.get("description")||null,basePrice:Number(f.get("price")),gstPercent:f.get("gst")?Number(f.get("gst")):null,discountAllowed:true}),"Billing service created");e.currentTarget.reset()};return <div className="hms-grid-2"><section className="hms-card"><div className="hms-card-head"><div><span>PRICE MASTER</span><h2>Services</h2></div></div><div className="hms-detail-list">{services.map((s:any)=><article key={s.id}><header><strong>{s.serviceName}</strong><span>{s.moduleCode}</span></header><p>{s.serviceCode} · {money(s.basePrice)} · GST {s.gstPercent||0}%</p></article>)}</div></section><form className="hms-card" onSubmit={submit}><div className="hms-card-head"><div><span>NEW SERVICE</span><h2>Add Billing Service</h2></div></div><div className="hms-form"><div className="hms-form-grid"><F n="code" l="Service code" req/><F n="name" l="Service name" req/><F n="module" l="Module code" req/><F n="price" l="Base price" type="number" req/><F n="gst" l="GST %" type="number"/></div><T n="description" l="Description"/><div className="hms-actions"><button disabled={busy}>Create Service</button></div></div></form></div>}
function InvoiceModal({invoice,busy,close,run}:any){const pay=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>recordBillingPayment(invoice.id,{paymentMode:f.get("mode"),amount:Number(f.get("amount")),transactionReference:f.get("reference")||null,remarks:f.get("remarks")||null}),"Payment recorded")};return <div className="hms-modal-bg" onMouseDown={close}><section className="hms-modal" onMouseDown={e=>e.stopPropagation()}><header><div><small>{invoice.invoiceNumber}</small><h2>{pn(invoice.patient)}</h2></div><button onClick={close}>×</button></header><div className="hms-detail-list">{invoice.items.map((x:any)=><article key={x.id}><header><strong>{x.description}</strong><span>{money(x.lineTotal||Number(x.quantity)*Number(x.unitPrice))}</span></header><p>{x.quantity} × {money(x.unitPrice)}</p></article>)}</div><form className="hms-form" onSubmit={pay}><div className="hms-form-grid"><label className="hms-field"><span>Payment mode</span><select name="mode"><option>CASH</option><option>CARD</option><option>UPI</option><option>BANK_TRANSFER</option><option>CHEQUE</option><option>INSURANCE</option><option>CORPORATE</option><option>OTHER</option></select></label><label className="hms-field"><span>Amount</span><input name="amount" type="number" max={Number(invoice.balanceAmount)} defaultValue={Number(invoice.balanceAmount)} required/></label><F n="reference" l="Transaction reference"/></div><T n="remarks" l="Remarks"/><div className="hms-actions"><button disabled={busy||Number(invoice.balanceAmount)<=0}>Record Payment</button></div></form></section></div>}
function F({n,l,type="text",req=false}:any){return <label className="hms-field"><span>{l}</span><input name={n} type={type} required={req}/></label>}function T({n,l}:any){return <label className="hms-field"><span>{l}</span><textarea name={n}/></label>}
