import { FormEvent, useEffect, useState } from "react";
import {
 createDepartmentAdmin,createDesignationAdmin,listBranchesAdmin,listDepartmentsAdmin,listDesignationsAdmin,updateDepartmentAdmin,
 type BranchRecord,type DepartmentRecord,type DesignationRecord
} from "../api/administration.api";
import "../styles/administration.css";
export default function DepartmentsPage(){
 const [departments,setDepartments]=useState<DepartmentRecord[]>([]),[designations,setDesignations]=useState<DesignationRecord[]>([]),[branches,setBranches]=useState<BranchRecord[]>([]),[tab,setTab]=useState<"departments"|"designations">("departments"),[open,setOpen]=useState(false),[editing,setEditing]=useState<DepartmentRecord|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const[d,g,b]=await Promise.all([listDepartmentsAdmin(),listDesignationsAdmin(),listBranchesAdmin()]);setDepartments(d.items);setDesignations(g.items);setBranches(b.items)}catch(e){setError(e instanceof Error?e.message:"Unable to load masters")}}useEffect(()=>{void load()},[]);
 async function saveDepartment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const body={branchId:f.get("branchId")||null,departmentName:f.get("departmentName"),departmentType:f.get("departmentType"),description:f.get("description")||null,status:f.get("status"),...(!editing?{departmentCode:f.get("departmentCode")}:{})};if(editing)await updateDepartmentAdmin(editing.id,body);else await createDepartmentAdmin(body);setSuccess("Department saved successfully.");setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save department")}finally{setBusy(false)}}
 async function saveDesignation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await createDesignationAdmin({designationCode:f.get("designationCode"),designationName:f.get("designationName"),departmentId:f.get("departmentId")||null,description:f.get("description")||null,status:"ACTIVE"});setSuccess("Designation created successfully.");e.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create designation")}finally{setBusy(false)}}
 return <div className="admin-page"><header className="admin-hero"><div><span className="admin-eyebrow">ORGANISATION MASTER</span><h1>Departments</h1><p>Clinical and non-clinical departments with branch mapping and employee designations.</p></div><button className="admin-primary" onClick={()=>{setEditing(null);setOpen(true)}}>+ Add Department</button></header>
 {error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="admin-kpis"><K l="Departments" v={departments.length}/><K l="Active" v={departments.filter(x=>x.status==="ACTIVE").length}/><K l="Designations" v={designations.length}/><K l="Branches" v={branches.length}/></section>
 <nav className="admin-tabs"><button className={tab==="departments"?"active":""} onClick={()=>setTab("departments")}>Departments</button><button className={tab==="designations"?"active":""} onClick={()=>setTab("designations")}>Designations</button></nav>
 {tab==="departments"?<section className="admin-card"><div className="admin-card-head"><div><span>DEPARTMENT MASTER</span><h2>Organisation Structure</h2></div></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Department</th><th>Code</th><th>Type</th><th>Branch</th><th>Status</th><th/></tr></thead><tbody>{departments.map(x=><tr key={x.id}><td><strong>{x.departmentName}</strong><small>{x.description||"No description"}</small></td><td>{x.departmentCode}</td><td>{x.departmentType}</td><td>{x.branch?.branchName||"Hospital-wide"}</td><td><span className={`admin-pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td><button className="admin-link" onClick={()=>{setEditing(x);setOpen(true)}}>Edit</button></td></tr>)}</tbody></table></div></section>:<div className="admin-split"><section className="admin-card"><div className="admin-card-head"><div><span>DESIGNATIONS</span><h2>Role Titles</h2></div></div><div className="admin-list">{designations.map(x=><div className="admin-list-item" key={x.id}><div><strong>{x.designationName}</strong><small>{x.designationCode} · {x.department?.departmentName||"All departments"}</small></div><span className={`admin-pill ${x.status.toLowerCase()}`}>{x.status}</span></div>)}</div></section><form className="admin-card" onSubmit={saveDesignation}><div className="admin-card-head"><div><span>NEW DESIGNATION</span><h2>Create Designation</h2></div></div><div className="admin-form"><div className="admin-grid"><F n="designationCode" l="Code *" req/><F n="designationName" l="Name *" req/><label className="admin-field wide"><span>Department</span><select name="departmentId"><option value="">All Departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.departmentName}</option>)}</select></label></div><T n="description" l="Description"/><div className="admin-actions"><button disabled={busy}>Create Designation</button></div></div></form></div>}
 {open&&<div className="admin-modal-bg"><form className="admin-modal" onSubmit={saveDepartment}><header><div><span>DEPARTMENT RECORD</span><h2>{editing?"Edit Department":"Add Department"}</h2></div><button type="button" className="admin-close" onClick={()=>setOpen(false)}>×</button></header><div className="admin-form"><div className="admin-grid">{!editing&&<F n="departmentCode" l="Department Code *" req/>}<F n="departmentName" l="Department Name *" d={editing?.departmentName||""} req/><label className="admin-field"><span>Type *</span><select name="departmentType" defaultValue={editing?.departmentType||"CLINICAL"}><option>CLINICAL</option><option>NON_CLINICAL</option><option>ADMINISTRATION</option><option>SUPPORT</option></select></label><label className="admin-field"><span>Branch</span><select name="branchId" defaultValue={editing?.branchId||""}><option value="">Hospital-wide</option>{branches.map(x=><option value={x.id} key={x.id}>{x.branchName}</option>)}</select></label><label className="admin-field"><span>Status</span><select name="status" defaultValue={editing?.status||"ACTIVE"}><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></label></div><T n="description" l="Description" d={editing?.description||""}/><div className="admin-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy}>Save Department</button></div></div></form></div>}
 </div>
}
function K({l,v}:{l:string;v:number}){return <article className="admin-kpi"><span>{l}</span><strong>{v}</strong></article>}function F({n,l,d="",req=false}:{n:string;l:string;d?:string;req?:boolean}){return <label className="admin-field"><span>{l}</span><input name={n} defaultValue={d} required={req}/></label>}function T({n,l,d=""}:{n:string;l:string;d?:string}){return <label className="admin-field wide"><span>{l}</span><textarea name={n} defaultValue={d}/></label>}
