import {FormEvent,useEffect,useMemo,useState} from "react";
import {createRadiologyProcedure,getRadiologyOrder,listRadiologyOrders,listRadiologyProcedures,saveRadiologyReport,scheduleRadiologyStudy,updateRadiologyReportStatus,updateRadiologyStudyStatus,type RadiologyOrder,type RadiologyProcedure} from "../api/radiology.api";
import "../styles/radiology.css";
const pn=(p:any)=>[p?.firstName,p?.middleName,p?.lastName].filter(Boolean).join(" ")||"Patient";const dt=(v?:string|null)=>v?new Date(v).toLocaleString("en-IN"):"—";
export default function RadiologyPage(){const [tab,setTab]=useState<"queue"|"procedures">("queue"),[orders,setOrders]=useState<RadiologyOrder[]>([]),[procedures,setProcedures]=useState<RadiologyProcedure[]>([]),[selected,setSelected]=useState<RadiologyOrder|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const [o,p]=await Promise.all([listRadiologyOrders(),listRadiologyProcedures()]);setOrders(o.items);setProcedures(p)}catch(e){setError(e instanceof Error?e.message:"Unable to load radiology")}}useEffect(()=>{void load()},[]);
 async function open(id:string){try{setSelected(await getRadiologyOrder(id))}catch(e){setError(e instanceof Error?e.message:"Unable to open order")}}
 async function run(fn:()=>Promise<any>,ok:string){try{setBusy(true);setError("");await fn();setMessage(ok);await load();if(selected)setSelected(await getRadiologyOrder(selected.id))}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
 const k=useMemo(()=>({total:orders.length,pending:orders.filter(o=>["ORDERED","SCHEDULED"].includes(o.status)).length,progress:orders.filter(o=>["CHECKED_IN","IN_PROGRESS"].includes(o.status)).length,completed:orders.filter(o=>o.status==="COMPLETED").length,reported:orders.filter(o=>o.status==="REPORTED").length}),[orders]);
 return <div className="hms-module-page"><header className="hms-module-hero"><div><span>RADIOLOGY INFORMATION SYSTEM</span><h1>Radiology</h1><p>Imaging order queue, study scheduling, modality workflow and structured radiology reporting.</p></div><button onClick={()=>setTab("procedures")}>Procedure Master</button></header>{error&&<div className="hms-alert error">{error}</div>}{message&&<div className="hms-alert success">{message}</div>}<section className="hms-kpis"><K l="Orders" v={k.total}/><K l="Pending / Scheduled" v={k.pending}/><K l="In progress" v={k.progress}/><K l="Completed" v={k.completed}/><K l="Reported" v={k.reported}/></section><nav className="hms-tabs"><button className={tab==="queue"?"active":""} onClick={()=>setTab("queue")}>Imaging Queue</button><button className={tab==="procedures"?"active":""} onClick={()=>setTab("procedures")}>Procedure Catalogue</button></nav>
 {tab==="queue"?<section className="hms-card"><div className="hms-card-head"><div><span>LIVE RIS QUEUE</span><h2>Imaging Orders</h2></div><button className="hms-action" onClick={()=>void load()}>Refresh</button></div><div className="hms-table-wrap"><table className="hms-table"><thead><tr><th>Order</th><th>Patient</th><th>Source</th><th>Procedure</th><th>Priority</th><th>Status</th><th>Requested</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.orderNumber}</strong></td><td><strong>{pn(o.patient)}</strong><small>{o.patient.uhid||""}</small></td><td>{o.ipdAdmissionId?<span className="hms-pill warn">IPD</span>:<span className="hms-pill">OPD</span>}</td><td>{o.items.map(i=>`${i.procedure.modality} · ${i.procedure.procedureName}`).join(", ")}</td><td>{o.priority}</td><td><span className={`hms-pill ${o.status==="REPORTED"?"good":""}`}>{o.status.replaceAll("_"," ")}</span></td><td>{dt(o.requestedAt)}</td><td><button className="hms-action" onClick={()=>void open(o.id)}>Open</button></td></tr>)}</tbody></table></div></section>:<ProcedureMaster procedures={procedures} busy={busy} run={run}/>}
 {selected&&<RadiologyModal order={selected} busy={busy} close={()=>setSelected(null)} run={run}/>}</div>}
function K({l,v}:{l:string;v:any}){return <article className="hms-kpi"><span>{l}</span><strong>{v}</strong></article>}
function ProcedureMaster({procedures,busy,run}:any){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createRadiologyProcedure({procedureCode:f.get("code"),procedureName:f.get("name"),modality:f.get("modality"),bodyPart:f.get("body")||null,laterality:f.get("laterality")||null,requiresContrast:f.get("contrast")==="on",requiresPreparation:f.get("prep")==="on",estimatedMinutes:f.get("minutes")?Number(f.get("minutes")):null,price:f.get("price")?Number(f.get("price")):null}),"Radiology procedure created");e.currentTarget.reset()};return <div className="hms-grid-2"><section className="hms-card"><div className="hms-card-head"><div><span>MASTER DATA</span><h2>Procedures</h2></div></div><div className="hms-detail-list">{procedures.map((p:any)=><article key={p.id}><header><strong>{p.procedureName}</strong><span>{p.modality}</span></header><p>{p.bodyPart||"—"} · ₹{Number(p.price||0).toLocaleString("en-IN")} · {p.estimatedMinutes||"—"} min</p></article>)}</div></section><form className="hms-card" onSubmit={submit}><div className="hms-card-head"><div><span>NEW PROCEDURE</span><h2>Add Procedure</h2></div></div><div className="hms-form"><div className="hms-form-grid"><F n="code" l="Code" req/><F n="name" l="Procedure name" req/><label className="hms-field"><span>Modality</span><select name="modality"><option>XRAY</option><option>CT</option><option>MRI</option><option>ULTRASOUND</option><option>MAMMOGRAPHY</option><option>FLUOROSCOPY</option><option>PET_CT</option><option>OTHER</option></select></label><F n="body" l="Body part"/><F n="laterality" l="Laterality"/><F n="minutes" l="Estimated minutes" type="number"/><F n="price" l="Price" type="number"/></div><label><input name="contrast" type="checkbox"/> Requires contrast</label> <label><input name="prep" type="checkbox"/> Requires preparation</label><div className="hms-actions"><button disabled={busy}>Create</button></div></div></form></div>}
function RadiologyModal({order,busy,close,run}:{order:RadiologyOrder;busy:boolean;close:()=>void;run:(f:()=>Promise<any>,m:string)=>void}){return <div className="hms-modal-bg" onMouseDown={close}><section className="hms-modal" onMouseDown={e=>e.stopPropagation()}><header><div><small>{order.orderNumber}</small><h2>{pn(order.patient)}</h2></div><button onClick={close}>×</button></header><div className="hms-detail-list">{order.items.map(item=><article key={item.id}><header><strong>{item.procedure.procedureName}</strong><span>{item.study?.status||"PENDING"}</span></header><p>{item.procedure.modality} · {item.procedure.bodyPart||""}</p>{item.study&&<StudyActions study={item.study} busy={busy} run={run}/>}</article>)}</div></section></div>}
function StudyActions({study,busy,run}:any){const sched=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>scheduleRadiologyStudy(study.id,{scheduledAt:f.get("at")}),"Study scheduled")};const report=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveRadiologyReport(study.id,{status:"DRAFT",findings:f.get("findings")||null,impression:f.get("impression")||null,recommendations:f.get("recommendations")||null}),"Report saved")};return <div>{study.status==="PENDING"&&<form className="hms-form" onSubmit={sched}><F n="at" l="Schedule date/time" type="datetime-local" req/><div className="hms-actions"><button disabled={busy}>Schedule</button></div></form>}{study.status==="SCHEDULED"&&<div className="hms-actions"><button onClick={()=>run(()=>updateRadiologyStudyStatus(study.id,{status:"CHECKED_IN"}),"Patient checked in")}>Check In</button></div>}{study.status==="CHECKED_IN"&&<div className="hms-actions"><button onClick={()=>run(()=>updateRadiologyStudyStatus(study.id,{status:"IN_PROGRESS"}),"Study started")}>Start Study</button></div>}{study.status==="IN_PROGRESS"&&<div className="hms-actions"><button onClick={()=>run(()=>updateRadiologyStudyStatus(study.id,{status:"COMPLETED"}),"Study completed")}>Complete Study</button></div>}{["COMPLETED","REPORTED"].includes(study.status)&&<form className="hms-form" onSubmit={report}><T n="findings" l="Findings"/><T n="impression" l="Impression"/><T n="recommendations" l="Recommendations"/><div className="hms-actions"><button disabled={busy}>Save Report</button>{study.report?.status==="DRAFT"&&<button type="button" onClick={()=>run(()=>updateRadiologyReportStatus(study.report.id,{status:"FINAL"}),"Report finalized")}>Finalize</button>}</div></form>}</div>}
function F({n,l,type="text",req=false}:any){return <label className="hms-field"><span>{l}</span><input name={n} type={type} required={req}/></label>}function T({n,l}:any){return <label className="hms-field"><span>{l}</span><textarea name={n}/></label>}
