import {FormEvent,useEffect,useMemo,useState} from "react";
import {createRoleAdmin,listPermissionsAdmin,listRolesAdmin,setRolePermissionsAdmin,updateRoleAdmin,type PermissionRecord,type RoleRecord} from "../api/administration.api";
import "../styles/administration.css";
export default function RolesPermissionsPage(){
 const[roles,setRoles]=useState<RoleRecord[]>([]),[permissions,setPermissions]=useState<PermissionRecord[]>([]),[selected,setSelected]=useState<RoleRecord|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const[r,p]=await Promise.all([listRolesAdmin(),listPermissionsAdmin()]);setRoles(r);setPermissions(p);if(selected){const fresh=r.find(x=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e){setError(e instanceof Error?e.message:"Unable to load roles and permissions")}}useEffect(()=>{void load()},[]);
 const grouped=useMemo(()=>permissions.reduce<Record<string,PermissionRecord[]>>((a,p)=>{(a[p.moduleCode]??=[]).push(p);return a},{}),[permissions]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await createRoleAdmin({roleCode:f.get("roleCode"),roleName:f.get("roleName"),description:f.get("description")||null,dataScope:f.get("dataScope"),status:"ACTIVE",permissionIds:[]});setOpen(false);setSuccess("Role created successfully.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create role")}finally{setBusy(false)}}
 async function savePermissions(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);setBusy(true);try{await setRolePermissionsAdmin(selected.id,f.getAll("permissionIds").map(String));setSuccess("Role permissions updated successfully.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update permissions")}finally{setBusy(false)}}
 return <div className="admin-page"><header className="admin-hero"><div><span className="admin-eyebrow">ROLE BASED ACCESS CONTROL</span><h1>Roles & Permissions</h1><p>Define hospital roles, data scope and exactly which application actions each role can perform.</p></div><button className="admin-primary" onClick={()=>setOpen(true)}>+ Create Role</button></header>{error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="admin-kpis"><K l="Roles" v={roles.length}/><K l="System Roles" v={roles.filter(x=>x.isSystemRole).length}/><K l="Hospital Roles" v={roles.filter(x=>!x.isSystemRole&&x.hospitalId).length}/><K l="Permissions" v={permissions.length}/></section>
 <div className="admin-split"><section className="admin-card"><div className="admin-card-head"><div><span>ACCESS ROLES</span><h2>Role Library</h2></div></div><div className="admin-list">{roles.map(r=><button className="admin-list-item" key={r.id} onClick={()=>setSelected(r)}><div><strong>{r.roleName}</strong><small>{r.roleCode} · {r.dataScope} · {r._count?.userRoles||0} user(s)</small></div><span className={`admin-pill ${r.status.toLowerCase()}`}>{r.isSystemRole?"SYSTEM":r.status}</span></button>)}</div></section>
 <section className="admin-card">{selected?<form onSubmit={savePermissions}><div className="admin-card-head"><div><span>{selected.isSystemRole?"READ-ONLY SYSTEM ROLE":"PERMISSION MATRIX"}</span><h2>{selected.roleName}</h2></div></div><div className="permission-grid">{Object.entries(grouped).map(([module,items])=><section className="permission-module" key={module}><h4>{module.replaceAll("_"," ").toUpperCase()}</h4>{items.map(p=><label className="permission-option" key={p.id}><input type="checkbox" name="permissionIds" value={p.id} disabled={selected.isSystemRole||selected.hospitalId===null} defaultChecked={selected.rolePermissions.some(x=>x.permissionId===p.id)}/><span>{p.actionCode}<small> · {p.permissionCode}</small></span></label>)}</section>)}</div>{!selected.isSystemRole&&selected.hospitalId&&<div className="admin-actions admin-form"><button disabled={busy}>Save Permissions</button></div>}</form>:<div className="admin-empty">Select a role to view its permission matrix.</div>}</section></div>
 {open&&<div className="admin-modal-bg"><form className="admin-modal" onSubmit={create}><header><div><span>HOSPITAL ROLE</span><h2>Create Custom Role</h2></div><button type="button" className="admin-close" onClick={()=>setOpen(false)}>×</button></header><div className="admin-form"><div className="admin-grid"><F n="roleCode" l="Role Code *" req/><F n="roleName" l="Role Name *" req/><label className="admin-field"><span>Data Scope *</span><select name="dataScope"><option>HOSPITAL</option><option>BRANCH</option><option>DEPARTMENT</option><option>OWN</option></select></label></div><T n="description" l="Description"/><div className="admin-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy}>Create Role</button></div></div></form></div>}
 </div>
}
function K({l,v}:{l:string;v:number}){return <article className="admin-kpi"><span>{l}</span><strong>{v}</strong></article>}function F({n,l,req=false}:{n:string;l:string;req?:boolean}){return <label className="admin-field"><span>{l}</span><input name={n} required={req}/></label>}function T({n,l}:{n:string;l:string}){return <label className="admin-field wide"><span>{l}</span><textarea name={n}/></label>}
