import {FormEvent,useEffect,useState} from "react";
import {createBranchAdmin,getHospitalSettings,listBranchesAdmin,updateBranchAdmin,updateHospitalSettings,type BranchRecord,type HospitalProfile} from "../api/administration.api";
import "../styles/administration.css";
export default function SettingsPage(){
 const[hospital,setHospital]=useState<HospitalProfile|null>(null),[branches,setBranches]=useState<BranchRecord[]>([]),[editBranch,setEditBranch]=useState<BranchRecord|null>(null),[openBranch,setOpenBranch]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const[h,b]=await Promise.all([getHospitalSettings(),listBranchesAdmin()]);setHospital(h);setBranches(b.items)}catch(e){setError(e instanceof Error?e.message:"Unable to load settings")}}useEffect(()=>{void load()},[]);
 async function saveHospital(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await updateHospitalSettings({displayName:f.get("displayName"),legalName:f.get("legalName"),registrationNumber:f.get("registrationNumber")||null,gstin:f.get("gstin")||null,pan:f.get("pan")||null,email:f.get("email"),phone:f.get("phone"),alternatePhone:f.get("alternatePhone")||null,addressLine1:f.get("addressLine1"),addressLine2:f.get("addressLine2")||null,city:f.get("city"),state:f.get("state"),country:f.get("country"),postalCode:f.get("postalCode"),timezone:f.get("timezone"),currencyCode:f.get("currencyCode")});setSuccess("Hospital settings updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}finally{setBusy(false)}}
 async function saveBranch(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const body={branchName:f.get("branchName"),branchType:f.get("branchType"),email:f.get("email")||null,phone:f.get("phone"),address:f.get("address"),city:f.get("city")||null,state:f.get("state")||null,postalCode:f.get("postalCode")||null,status:f.get("status")||"ACTIVE",...(!editBranch?{branchCode:f.get("branchCode"),isMainBranch:false}:{})};if(editBranch)await updateBranchAdmin(editBranch.id,body);else await createBranchAdmin(body);setSuccess("Branch saved successfully.");setOpenBranch(false);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save branch")}finally{setBusy(false)}}
 if(!hospital)return <div className="admin-page">{error?<div className="admin-alert error">{error}</div>:<div className="admin-empty">Loading settings...</div>}</div>;
 return <div className="admin-page"><header className="admin-hero"><div><span className="admin-eyebrow">HOSPITAL CONFIGURATION</span><h1>Settings</h1><p>Hospital identity, statutory information, address, localisation and branch configuration. Settings remain tenant-specific.</p></div><button className="admin-primary" onClick={()=>{setEditBranch(null);setOpenBranch(true)}}>+ Add Branch</button></header>{error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="admin-kpis"><K l="Hospital Code" v={hospital.hospitalCode}/><K l="Branches" v={branches.length}/><K l="Timezone" v={hospital.timezone}/><K l="Currency" v={hospital.currencyCode}/></section>
 <div className="settings-grid"><form className="admin-card" onSubmit={saveHospital}><div className="admin-card-head"><div><span>ORGANISATION PROFILE</span><h2>Hospital Details</h2></div></div><div className="admin-form"><div className="admin-grid"><F n="displayName" l="Display Name *" d={hospital.displayName} req/><F n="legalName" l="Legal Name *" d={hospital.legalName} req/><F n="registrationNumber" l="Registration Number" d={hospital.registrationNumber||""}/><F n="gstin" l="GSTIN" d={hospital.gstin||""}/><F n="pan" l="PAN" d={hospital.pan||""}/><F n="email" l="Email *" type="email" d={hospital.email} req/><F n="phone" l="Phone *" d={hospital.phone} req/><F n="alternatePhone" l="Alternate Phone" d={hospital.alternatePhone||""}/><F n="addressLine1" l="Address Line 1 *" d={hospital.addressLine1} req/><F n="addressLine2" l="Address Line 2" d={hospital.addressLine2||""}/><F n="city" l="City *" d={hospital.city} req/><F n="state" l="State *" d={hospital.state} req/><F n="country" l="Country *" d={hospital.country} req/><F n="postalCode" l="Postal Code *" d={hospital.postalCode} req/><F n="timezone" l="Timezone *" d={hospital.timezone} req/><F n="currencyCode" l="Currency *" d={hospital.currencyCode} req/></div><div className="admin-actions"><button disabled={busy}>Save Hospital Settings</button></div></div></form>
 <section className="admin-card"><div className="admin-card-head"><div><span>BRANCH CONFIGURATION</span><h2>Hospital Locations</h2></div></div><div className="admin-list">{branches.map(b=><div className="admin-list-item" key={b.id}><div><strong>{b.branchName}</strong><small>{b.branchCode} · {b.phone} · {b.city||"—"}</small></div><div><span className={`admin-pill ${b.status.toLowerCase()}`}>{b.isMainBranch?"MAIN":b.status}</span> <button className="admin-link" onClick={()=>{setEditBranch(b);setOpenBranch(true)}}>Edit</button></div></div>)}</div></section></div>
 {openBranch&&<div className="admin-modal-bg"><form className="admin-modal" onSubmit={saveBranch}><header><div><span>BRANCH SETTINGS</span><h2>{editBranch?"Edit Branch":"Add Branch"}</h2></div><button type="button" className="admin-close" onClick={()=>setOpenBranch(false)}>×</button></header><div className="admin-form"><div className="admin-grid">{!editBranch&&<F n="branchCode" l="Branch Code *" req/>}<F n="branchName" l="Branch Name *" d={editBranch?.branchName} req/><F n="branchType" l="Branch Type *" d={editBranch?.branchType||"HOSPITAL"} req/><F n="email" l="Email" type="email" d={editBranch?.email||""}/><F n="phone" l="Phone *" d={editBranch?.phone} req/><F n="city" l="City" d={editBranch?.city||""}/><F n="state" l="State" d={editBranch?.state||""}/><F n="postalCode" l="Postal Code" d={editBranch?.postalCode||""}/><label className="admin-field"><span>Status</span><select name="status" defaultValue={editBranch?.status||"ACTIVE"}><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></label></div><label className="admin-field wide"><span>Address *</span><textarea name="address" defaultValue={editBranch?.address||""} required/></label><div className="admin-actions"><button type="button" className="secondary" onClick={()=>setOpenBranch(false)}>Cancel</button><button disabled={busy}>Save Branch</button></div></div></form></div>}
 </div>
}
function K({l,v}:{l:string;v:string|number}){return <article className="admin-kpi"><span>{l}</span><strong>{v}</strong></article>}function F({n,l,d="",type="text",req=false}:{n:string;l:string;d?:string;type?:string;req?:boolean}){return <label className="admin-field"><span>{l}</span><input name={n} type={type} defaultValue={d} required={req}/></label>}
